### PR TITLE
ec2: add EBSOptimized option to RunInstances

### PR DESCRIPTION
**Pull request by fsouza**
Allowing users to specify this option when running new instances.

### CODE REVIEW

**Comment by dimitern** [comment]
This looks good, however there are no tests that actually verify EBSOptimized is included in RunInstances request. Can you add a test for this or modify an existing one?

**Comment by fsouza** [comment]
Sure!

**Comment by fsouza** [comment]
I've just updated a test. Should I change one of the integration tests as well, or is it enough?

**Comment by dimitern** [comment]
That's enough I think. I'll merge you changes. Thanks!

**Pull request merged**
